In [ ]:
#!python -m cProfile -s cumulative testExtract1.py
!python  testExtract1_numpy.py

In [ ]:
!python  testCluster1.py

In [ ]:
!python  testSamplesCluster1.py

In [ ]:
head2 = ['frameid','trackid']
head2.extend(list(range(10-2)))
head2

In [38]:
import numpy as np
from sklearn.preprocessing import scale
from sklearn.preprocessing import MinMaxScaler

a = np.arange(10,20)
b = np.arange(20,30)
c = np.arange(50,60)
d = np.array([a,b,c])
print(d)
my_minmax_scaler = MinMaxScaler(feature_range=(0, 1))
e = my_minmax_scaler.fit_transform(d)
e

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [50 51 52 53 54 55 56 57 58 59]]


array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25],
       [1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ]])